This notebook is for doing required calculation in Q4. I have just included this as a refrence.

In [1]:
import numpy as np
from numpy.linalg import inv

I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [0]:
def J_mu (g, P):
  alpha = 0.1
  I = np.eye(2)  
  return inv(I - alpha * P).dot(g)

In [0]:
#Policy 1
g = np.array ([[0.5 * -9 + 0.5 * -3] , 
               [0.6 * 7 + 0.4 * -3]])
# g.reshape(1, 2)
print (g)

P = np.array([[0.5 , 0.5], 
              [0.4, 0.6]])

print (P)

print (J_mu(g, P))

[[-6.]
 [ 3.]]
[[0.5 0.5]
 [0.4 0.6]]
[[-6.16161616]
 [ 2.92929293]]


In [0]:
#Value 
# print(TJ (g, P, J))

In [0]:

#Policy 2
g = np.array ([[0.8 * -4 + 0.2 * -4] , 
               [0.7 * -1 + 0.3 * 19]])
# g.reshape(1, 2)
print (g)

P = np.array([[0.8 , 0.2], 
              [0.7, 0.3]])

print (P)

print (J_mu(g, P))

[[-4.]
 [ 5.]]
[[0.8 0.2]
 [0.7 0.3]]
[[-4.24242424]
 [ 4.84848485]]


In [0]:
#Policy 3
g = np.array ([[0.5 * -9 + 0.5 * -3] , 
               [0.7 * -1 + 0.3 * 19]])
# g.reshape(1, 2)
print (g)

P = np.array([[0.5 , 0.5], 
              [0.7, 0.3]])

print (P)

print (J_mu(g, P))

[[-6.]
 [ 5.]]
[[0.5 0.5]
 [0.7 0.3]]
[[-6.06753813]
 [ 4.7167756 ]]


In [0]:
#Policy 4
g = np.array ([[0.8 * -4 + 0.2 * -4] , 
               [0.6 * 7 + 0.4 * -3]])
# g.reshape(1, 2)
print (g)

P = np.array([[0.8 , 0.2], 
              [0.4, 0.6]])

print (P)

print (J_mu(g, P))

[[-4.]
 [ 3.]]
[[0.8 0.2]
 [0.4 0.6]]
[[-4.28240741]
 [ 3.00925926]]


In [0]:
def TJ (g, P, J):
  alpha = 0.9
  return g + alpha * P.dot(J)

J = np.array([[-9.24],
              [0.65]])
print (J)

[[-9.24]
 [ 0.65]]


In [0]:
#Policy 1
g = np.array ([[0.5 * -9 + 0.5 * -3] , 
               [0.6 * 7 + 0.4 * -3]])

P = np.array([[0.5 , 0.5], 
              [0.4, 0.6]])
print(TJ (g, P, J))

[[-9.8655]
 [ 0.0246]]


In [0]:
#Policy 2
g = np.array ([[0.8 * -4 + 0.2 * -4] , 
               [0.7 * -1 + 0.3 * 19]])
P = np.array([[0.8 , 0.2], 
              [0.7, 0.3]])

print(TJ (g, P, J))

[[-10.5358]
 [ -0.6457]]
